language: node_js
node_js:
- '10'
before_deploy: npm run build && npm run cp:pkg && cd lib
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  skip_cleanup: true
  api_key:
    secure: "$NPM_TOKEN"
  on:
    tags: true
  tag: next
